#from xml: server-port=9090
server:
  port: 9090
  servlet:
    context-path: /myapp

spring:
  datasource:
    url: jdbc:postgresql://java2010usf.cvxdjn3idij1.us-east-2.rds.amazonaws.com/postgres?currentSchema=hacking_hobbits
    username: JHeermance
    password: AWSdatabase1
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
